# Generated by Django 5.0.7 on 2024-10-18 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_booking_created_at_booking_is_used_menu_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
