# Generated by Django 5.0.7 on 2024-10-20 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_cartitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
