# Generated by Django 5.0.7 on 2024-10-20 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_remove_cartitem_menu_item_delete_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(default='+911234567890', max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid number. E.g., '+919876543210' or '9876543210'.", regex='^\\+?91?\\d{10}$')]),
        ),
    ]
