# Generated by Django 5.0.7 on 2024-10-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_booking_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('Brunch', 'brunch'), ('Appetizer', 'appetizer'), ('Sides', 'sides'), ('Entrees', 'entrees'), ('Specials', 'specials'), ('Vegan', 'vegan'), ('Beverages', 'beverages'), ('Desserts', 'desserts')], default='entrees', max_length=20),
        ),
    ]
