# Generated by Django 5.0.7 on 2024-10-27 13:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_menu_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['booking_date', 'booking_time']},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid number. E.g., '+919876543210' or '9876543210'.", regex='^\\+?91?\\d{10}$')]),
        ),
    ]
