# Generated by Django 5.0.7 on 2024-11-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_remove_cartitem_cart_remove_cartitem_menu_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='comment',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
