# Generated by Django 5.0.7 on 2024-11-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0020_alter_order_total_price_alter_orderitem_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_price',
            field=models.IntegerField(null=True),
        ),
    ]
