# Generated by Django 5.1 on 2024-11-04 18:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0021_alter_order_total_price_alter_orderitem_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be a valid number. E.g., '+919876543210' ", regex='^\\d{10}$')]),
        ),
    ]
